services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://${DB_ROOT_USER}:${DB_ROOT_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      EXCHANGE_RATE_API_KEY: ${EXCHANGE_RATE_API_KEY}
      EXTERNAL_API_BASE_URL: ${EXTERNAL_API_BASE_URL}
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: mariadb:10.5
    restart: always
    environment:
      DB_ROOT_USER: ${DB_ROOT_USER}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
